// <auto-generated />
using System;
using Competiciones.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Competiciones.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303133011_updateCompeticion")]
    partial class updateCompeticion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CompeticionEquipo", b =>
                {
                    b.Property<int>("CompeticionesId")
                        .HasColumnType("int");

                    b.Property<int>("EquiposId")
                        .HasColumnType("int");

                    b.HasKey("CompeticionesId", "EquiposId");

                    b.HasIndex("EquiposId");

                    b.ToTable("CompeticionEquipo");
                });

            modelBuilder.Entity("Competiciones.Models.Entities.Competicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Competiciones");
                });

            modelBuilder.Entity("Competiciones.Models.Entities.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<string>("RutaEscudo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("Competiciones.Models.Entities.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Altura")
                        .HasColumnType("int");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("LastNames")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<float?>("Peso")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("PaisId");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("Competiciones.Models.Entities.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("rutaBandera")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("CompeticionEquipo", b =>
                {
                    b.HasOne("Competiciones.Models.Entities.Competicion", null)
                        .WithMany()
                        .HasForeignKey("CompeticionesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Competiciones.Models.Entities.Equipo", null)
                        .WithMany()
                        .HasForeignKey("EquiposId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Competiciones.Models.Entities.Competicion", b =>
                {
                    b.HasOne("Competiciones.Models.Entities.Pais", "Pais")
                        .WithMany("Competiciones")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Competiciones.Models.Entities.Equipo", b =>
                {
                    b.HasOne("Competiciones.Models.Entities.Pais", "Pais")
                        .WithMany("Equipos")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Competiciones.Models.Entities.Jugador", b =>
                {
                    b.HasOne("Competiciones.Models.Entities.Equipo", "Equipo")
                        .WithMany("Jugadores")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Competiciones.Models.Entities.Pais", "Pais")
                        .WithMany("Jugaores")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("Competiciones.Models.Entities.Equipo", b =>
                {
                    b.Navigation("Jugadores");
                });

            modelBuilder.Entity("Competiciones.Models.Entities.Pais", b =>
                {
                    b.Navigation("Competiciones");

                    b.Navigation("Equipos");

                    b.Navigation("Jugaores");
                });
#pragma warning restore 612, 618
        }
    }
}
